# Generated by Django 5.1.1 on 2025-01-19 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_friend_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req', to=settings.AUTH_USER_MODEL, verbose_name='Запросы'),
        ),
    ]
