# Generated by Django 5.1.1 on 2025-01-19 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requested',
        ),
        migrations.AddField(
            model_name='user',
            name='requested',
            field=models.ManyToManyField(blank=True, related_name='req', to=settings.AUTH_USER_MODEL, verbose_name='Запросы'),
        ),
    ]
