# Generated by Django 5.1.1 on 2024-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['text', 'likes', 'group', 'create_date'], name='main_post_text_b9eee0_idx'),
        ),
    ]
