# Generated by Django 5.1.1 on 2024-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_options_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=35, unique=True, verbose_name='Название'),
        ),
    ]
