# Generated by Django 5.1.1 on 2024-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_alter_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Статус'),
        ),
    ]
