# Generated by Django 5.1.1 on 2024-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Теги'),
        ),
    ]
