# Generated by Django 5.1.1 on 2024-09-19 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_img_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='main_commen_likes_1aca9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='main_post_text_cb3b81_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['text', 'group', '-create_date'], name='main_post_text_ce7f2b_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='clikes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='plikes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
