# Generated by Django 5.1.1 on 2024-10-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_post_group_alter_post_tags_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-pk']},
        ),
    ]
