# Generated by Django 5.1.1 on 2025-03-09 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='moder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sup_mod', to=settings.AUTH_USER_MODEL, verbose_name='Ответчик'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
